---
# tasks file for web-stg
- name: Install system updates for centos systems
  yum: 
    name=*
    state=latest 
    update_cache=yes
- name: Install appache
  yum:
    name: httpd
    state: latest
- name: Install PHP
  yum:
    name: php
    state: latest
- name: start the service
  service:
    name: httpd
    state: started
    enabled: true
- name: allow the service from firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  notify: restart firewalld
- name: copy index file
  copy:
    src: ./index.php
    dest: /var/www/html/
  notify: restart httpd
- name: change hostname
  hostname: 
    name: "{{ hostname[inventory_hostname] }}"